### ISSUE TITLE
Add support for HARDWARE_TOUCHPAD_GO

### ISSUE THREAD

**Issue by rwhitby** [dtzWill/xserver_webos#6]
In all places where a check is made for HARDWARE_TOUCHPAD, please also check for HARDWARE_TOUCHPAD_GO

**Comment by dtzWill** [comment]
Can you confirm that this works as expected?
I posted a built armv7 binary from 186645e5f7d0262cf74b2b63f57b721d6381e934 here: http://ompldr.org/vY2xzcw .

**Comment by rwhitby** [comment]
Visually inspected, no longer have the hardware to test.
